Preguntas/Models/Dominio/Juego.cs
using Binit.Infraestructura.Website.Models.Dominio.General;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio
{
    public class Juego : Entidad
    {
        public Juego() { }
        public Juego(JuegoABMViewModel viewmodel)
        {
            Id = viewmodel.Id;
            Nombre = viewmodel.TipoDeJuego;
        }
        public JuegoABMViewModel ConvertirAViewModel()
        {
            var viewmodel = new JuegoABMViewModel();
            viewmodel.Id = Id;
            viewmodel.TipoDeJuego = Nombre;

            return viewmodel;
        }
        public virtual ICollection<Pregunta> Preguntas { get; set; }
    }
}

Preguntas/Controllers/JuegoController.cs
using Preguntas.Models;
using Preguntas.Models.Dominio;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Preguntas.Controllers
{
    public class JuegoController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Juego
        public ActionResult Index()
        {
            return Content("Juego creado! <a href='/Juego/Create'>volver</a>");
        }
        public ActionResult Create()
        {
            var model = new JuegoABMViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(JuegoABMViewModel model)
        {
            if (ModelState.IsValid)
            {
                var juegos = new Juego(model);
                db.Juegos.Add(juegos);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Preguntas/Views/Juego/Create.cshtml
<!--CREATE DE JUEGO -->
@model Preguntas.Models.Dominio.ViewModels.Preguntas.JuegoABMViewModel

<div class="container">
            @using (Html.BeginForm("Create", "Juego", FormMethod.Post, new { @id = "form" }))
            {
                <div class="form-row mt-2">
                    <div class="col-md-6 form-group">
                        <label for="Comentario" class="col-form-label">Nombre</label>
                        @Html.TextBoxFor(m => m.TipoDeJuego , new { @class = "form-control" })
                    </div>

                    <button class="btn btn-primary">Guardar</button>
                </div>
            }
</div>