Preguntas/Models/Dominio/ViewModels/Preguntas/JuegoFinalizadoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class JuegoFinalizadoViewModel
    {
        public string Usuario { get; set; }
        public string Juego { get; set; }
        public IEnumerable<PreguntaEstadisticaViewModel> PreguntaEstadistica { get; set; }
        public int PuntajeTotal { get; set; }
    }
    public class JuegoFinalizadoMobileViewModel
    {
        public Guid IdCategoria { get; set; }
        public string Usuario { get; set; }
        public string Juego { get; set; }
        public IEnumerable<PreguntaEstadisticaViewModel> PreguntaEstadistica { get; set; }
        public int PuntajeTotal { get; set; }
        public string Finalizado { get; set; }
    }
}

Preguntas/Controllers/JugarController.cs
using cuidarlos.web.Controllers;
using Microsoft.AspNet.Identity;
using Preguntas.Models.Dominio;
using Preguntas.Models.Dominio.ViewModels;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using Preguntas.Models.General;
using System;
using System.Linq;
using System.Web.Mvc;

namespace Preguntas.Controllers
{
    public class JugarController : BaseController
    {
        // GET: Jugar
        // Muestra las categorias para comenzar
        public ActionResult Index()
        {
            var seleccionarjuegos = db.Juegos.Select(Juego => new SelectBoxViewModel
            {
                Id = Juego.Id,
                Nombre = Juego.Nombre
            }).ToList();
            return View(seleccionarjuegos);
        }

        public ActionResult IndexMobile()
        {
            var seleccionarjuegos = db.Juegos.Select(Juego => new SelectBoxViewModel
            {
                Id = Juego.Id,
                Nombre = Juego.Nombre,
            }).ToList();

            return Json(new { Result = seleccionarjuegos, Error = "" }, JsonRequestBehavior.AllowGet);
        }

        //Una vez seleccionada la categoria recibe el ID de la categoria y muestra las preguntas
        public ActionResult ComenzarAJugar(Guid Id)
        {
            var juego = db.Juegos.Find(Id);
            var userid = User.Identity.GetUserId();

            var preguntasContestadas = db.PreguntaPorRespuesta.Where(pr =>
                        pr.Juego.Id == Id &&
                        pr.Usuario.UsuarioApp.Id == userid
                ).ToList();

            var preguntaAContestar = new Pregunta();

            foreach (var pregunta in juego.Preguntas)
            {
                var existe = preguntasContestadas.FirstOrDefault(p => p.Pregunta.Id == pregunta.Id);

                if (existe == null)
                {
                    preguntaAContestar = pregunta;
                    break;
                }
            }

            if (preguntaAContestar.Nombre == null)
            {
                return RedirectToAction("JuegoFinalizado", new { Id = Id });  //CONTESTO TODAS LAS PREGUNTAS TODAS LAS PREGUNTAS
            }

            var model = new PreguntaJuegoViewModel();
            model.JuegoId = Id;
            model.PreguntaJuego = preguntaAContestar.CovertirAViewModel();
            model.RespuestaCorrecta = preguntaAContestar.Respuestas.FirstOrDefault(r => r.EsCorrecta).Id;
            model.RespuestaJuego = preguntaAContestar.Respuestas.Select(r => new RespuestaViewModel
            {
                Id = r.Id,
                Nombre = r.Nombre
            }).ToList();

            return View(model);
        }

        public ActionResult ComenzarAJugarMobile()
        {
            Guid id = Newtonsoft.Json.JsonConvert.DeserializeObject<Guid>(this.Contenido);
            var juego = db.Juegos.Find(id);

            var preguntasContestadas = db.PreguntaPorRespuesta.Where(pr =>
                        pr.Juego.Id == id &&
                        pr.Usuario.UsuarioApp.Id == usuarioId
                ).ToList();

            var preguntaAContestar = new Pregunta();

            foreach (var pregunta in juego.Preguntas)
            {
                var existe = preguntasContestadas.FirstOrDefault(p => p.Pregunta.Id == pregunta.Id);

                if (existe == null)
                {
                    preguntaAContestar = pregunta;
                    break;
                }
            }

            if (preguntaAContestar.Nombre == null)
            {
                return Json(new { Result = "Termino", Error = "" }, JsonRequestBehavior.AllowGet);  //CONTESTO TODAS LAS PREGUNTAS
                //return RedirectToAction("JuegoFinalizadoMobile", new { Id = Id });  //CONTESTO TODAS LAS PREGUNTAS
            }

            var model = new PreguntaJuegoViewModel();
            model.JuegoId = id;
            model.PreguntaJuego = preguntaAContestar.CovertirAViewModel();
            model.RespuestaCorrecta = preguntaAContestar.Respuestas.FirstOrDefault(r => r.EsCorrecta).Id;
            model.RespuestaJuego = preguntaAContestar.Respuestas.Select(r => new RespuestaViewModel
            {
                Id = r.Id,
                Nombre = r.Nombre
            }).ToList();

            return Json(new { Result = model, Error = "" }, JsonRequestBehavior.AllowGet);
        }

        //Cuando el usario contesta 
        [HttpPost]
        public ActionResult RespuestaPregunta()
        {
            var model = Newtonsoft.Json.JsonConvert.DeserializeObject<ContestarViewModel>(this.Contenido);
            var usuario = db.Usuarios.Where(u => u.UsuarioApp.Id == usuarioId).First();

            var respuestaPregunta = new PreguntaPorRespuesta(model, db);
            respuestaPregunta.Usuario = usuario;

            db.PreguntaPorRespuesta.Add(respuestaPregunta);
            db.SaveChanges();

            return Json(new { Result = "OK", model = model, Error = "" }, JsonRequestBehavior.AllowGet);
        }

        //Muestra los puntajes
        public ActionResult JuegoFinalizado(Guid Id)
        {
            var usuarioId = User.Identity.GetUserId();
            var usuarioNickname = db.Usuarios.FirstOrDefault(u => u.UsuarioApp.Id == usuarioId);
            var nombreJuego = db.Juegos.FirstOrDefault(j => j.Id == Id);

            var contestoAlgunaBien = db.PreguntaPorRespuesta.Any(u => u.Usuario.UsuarioApp.Id == usuarioId
            && u.Juego.Id == Id
            && u.Respuesta.EsCorrecta == true);
 
            var puntajeTotal = 0;
            if (contestoAlgunaBien)
            {
                puntajeTotal = db.PreguntaPorRespuesta.Where(u => u.Usuario.UsuarioApp.Id == usuarioId)
                    .Where(j => j.Juego.Id == Id).Where(r => r.Respuesta.EsCorrecta == true).Sum(s => s.Pregunta.Puntaje);
            }

            //respuestas usuario
            var respuestasElegidas = db.PreguntaPorRespuesta.Where(u => u.Usuario.UsuarioApp.Id == usuarioId
            && u.Juego.Id == Id);

            //preguntas usuario
            var preguntasUsuario = nombreJuego.Preguntas.Select(pu => new PreguntaEstadisticaViewModel {
                PreguntaEstadisticaTexto = pu.Nombre,
                PuntajePreguntaEstadistica = pu.Puntaje,
                RespuestaEstadistica = pu.Respuestas.Select(r => new RespuestaEstadisticaViewModel
                {
                    RespuestaTexto = r.Nombre,
                    EsCorrecta = r.EsCorrecta,
                    RespuestaElegida = respuestasElegidas.Any(re => re.Respuesta.Id == r.Id)
                })
            }).ToList();

            //preguntas
            var preguntas = new JuegoFinalizadoViewModel();
            preguntas.Juego = nombreJuego.Nombre;
            preguntas.Usuario = usuarioNickname.NickName;
            preguntas.PuntajeTotal = puntajeTotal;
            preguntas.PreguntaEstadistica = preguntasUsuario;

            return View(preguntas);
        }

        public ActionResult JuegoFinalizadoMobile()
        {
            OneSignalController.SendNotificationToCuidarlos();
            Guid id = Newtonsoft.Json.JsonConvert.DeserializeObject<Guid>(this.Contenido);
            var usuarioNickname = db.Usuarios.FirstOrDefault(u => u.UsuarioApp.Id == usuarioId);
            var nombreJuego = db.Juegos.FirstOrDefault(j => j.Id == id);

            var contestoAlgunaBien = db.PreguntaPorRespuesta.Any(u => u.Usuario.UsuarioApp.Id == usuarioId
            && u.Juego.Id == id
            && u.Respuesta.EsCorrecta == true);

            var puntajeTotal = 0;
            if (contestoAlgunaBien)
            {
                puntajeTotal = db.PreguntaPorRespuesta.Where(u => u.Usuario.UsuarioApp.Id == usuarioId)
                    .Where(j => j.Juego.Id == id).Where(r => r.Respuesta.EsCorrecta == true).Sum(s => s.Pregunta.Puntaje);
            }

            //respuestas usuario
            var respuestasElegidas = db.PreguntaPorRespuesta.Where(u => u.Usuario.UsuarioApp.Id == usuarioId
            && u.Juego.Id == id);

            //preguntas usuario
            var preguntasUsuario = nombreJuego.Preguntas.Select(pu => new PreguntaEstadisticaViewModel
            {
                PreguntaEstadisticaTexto = pu.Nombre,
                PuntajePreguntaEstadistica = pu.Puntaje,
                RespuestaEstadistica = pu.Respuestas.Select(r => new RespuestaEstadisticaViewModel
                {
                    RespuestaTexto = r.Nombre,
                    EsCorrecta = r.EsCorrecta,
                    RespuestaElegida = respuestasElegidas.Any(re => re.Respuesta.Id == r.Id)
                })
            }).ToList();

            //preguntas
            var preguntas = new JuegoFinalizadoMobileViewModel();
            preguntas.Finalizado = "OK";
            preguntas.IdCategoria = id;
            preguntas.Juego = nombreJuego.Nombre;
            preguntas.Usuario = usuarioNickname.NickName;
            preguntas.PuntajeTotal = puntajeTotal;
            preguntas.PreguntaEstadistica = preguntasUsuario;

            //return View(preguntas);
            return Json(new { Result = preguntas, Error = "" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Preguntas/Views/Jugar/ComenzarAJugar.cshtml
@model Preguntas.Models.Dominio.ViewModels.Preguntas.PreguntaJuegoViewModel

<div class="container">
    <div class="text-center row">
        <h1 id="@Model.PreguntaJuego.Id">@Model.PreguntaJuego.Nombre</h1>
    </div>
    <div class="text-center row">
        @foreach (var item in Model.RespuestaJuego)
            {
            <h3 class="resp">@(item.Nombre)</h3> <a class="respuesta btn btn-info" id="@(item.Id)">Responder</a>
        }
    </div>

</div>
@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {

        var juegoid = '@Model.JuegoId';
        var preguntajuego = '@Model.PreguntaJuego.Id';
        var correcta = '@Model.RespuestaCorrecta';

        $('.respuesta').on("click", function () {
            var url = '@(Url.Action("RespuestaPregunta", "Jugar"))';
            var id = $(this).attr('id');

            var respuestaDelUsuario = {
                JuegoId: juegoid,
                PreguntaId: preguntajuego,
                RespuestaId: id
            }

            if (id == correcta) {
                $("#" + id).removeClass("btn-info").addClass("btn-success");
            }

            else {
                $("#" + id).removeClass("btn-info").addClass("btn-danger");
                $("#" + correcta).removeClass("btn-info").addClass("btn-success");
            }

            $.ajax({
                type: "POST",
                url: url,
                data: { model: respuestaDelUsuario },
                success: setTimeout(function (Result) {
                    location.reload();
                }, 1750)
            });
        });
    });
</script>}

Preguntas/Views/Jugar/Index.cshtml
@model IEnumerable<Preguntas.Models.General.SelectBoxViewModel>

<div class="container">
    <div class="col-md-offset-3 col-md-6">
        <h3 class="text-center">Elige una categoria de preguntas</h3>
        <div id="ListaJuegos">
            @foreach (var juego in Model)
            {
                <a style="font-size:18px" href="@Url.Action("ComenzarAJugar")/@(juego.Id)" class="btn btn-info btn-block">@juego.Nombre</a>
            }
        </div>
    </div>
</div>

@section Scripts {
<script type="text/javascript">
    $(document).ready(function () {
        $('.btn').click(function () {
            var juegoid = $(this).attr('id')
            console.log(juegoid)
        });
    }); //document ready
</script>
}

Preguntas/Views/Jugar/JuegoFinalizado.cshtml
@model Preguntas.Models.Dominio.ViewModels.Preguntas.JuegoFinalizadoViewModel
<div class="container">
    <h3 class="text-center">Felicidades<strong> @Model.Usuario!</strong></h3>
    <h3 class="text-center">El juego fue <strong>@Model.Juego</strong></h3>
    <h4 class="alert alert-info">Puntuacion total: @Model.PuntajeTotal</h4>

    <br />
    <div class="row well text-center">
            @foreach (var item in Model.PreguntaEstadistica)
            {   <dl>
                <dt>@item.PreguntaEstadisticaTexto</dt>
                @foreach (var resp in item.RespuestaEstadistica)
                {
                    if (resp.EsCorrecta)
                    {
                        <dd class="text-success">@resp.RespuestaTexto <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></dd>
                    }
                    else if (!resp.EsCorrecta && resp.RespuestaElegida)
                    {
                        <dd class="text-danger">@resp.RespuestaTexto <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></dd>
                    }
                    else
                    {
                        <dd>@resp.RespuestaTexto</dd>
                    }
                }
            </dl>
            <span><ins>Puntuacion:</ins>@item.PuntajePreguntaEstadistica</span>
            }
    </div>
    <br />
    
    <a href="../Index" class="btn btn-info btn-lg">Volver</a>
</div>