Preguntas/Models/Dominio/Pregunta.cs
using Binit.Infraestructura.Website.Models.Dominio.General;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using Preguntas.Models.ViewModels.Preguntas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio
{
    public class Pregunta : Entidad
    {
        public Pregunta()
        {
            Respuestas = new List<Respuesta>();
        }
        public Pregunta(PreguntaABMViewModel viewmodel, ApplicationDbContext db)
        {
            Nombre = viewmodel.Nombre;
            Puntaje = viewmodel.Puntaje;
            Juegos = new List<Juego>();
            Juegos.Add(db.Juegos.Find(viewmodel.Juego));  //busca el juego enviado en la vista

            if (Respuestas == null)
                Respuestas = new List<Respuesta>();
            foreach (var respuestavm in viewmodel.Respuestas)
            {
                var respuesta = new Respuesta(respuestavm);
                Respuestas.Add(respuesta);
            }
        }
        public PreguntaViewModel CovertirAViewModel()
        {
            var viewmodel = new PreguntaViewModel();
            viewmodel.Id = Id;
            viewmodel.Nombre = Nombre;
            viewmodel.Puntaje = Puntaje;
            viewmodel.Juego = JuegoId;
            viewmodel.RepuestasDeLaPregunta = Respuestas.Select(r => r.Id).ToList();

            return viewmodel;
        }

        public virtual ICollection<Juego> Juegos { get; set; }
        public virtual ICollection<Respuesta> Respuestas { get; set; }
        public int Puntaje { get; set; }
        public virtual Guid JuegoId { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/JuegoABMViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class JuegoABMViewModel
    {
        public Guid Id { get; set; }
        public string TipoDeJuego { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/JuegoFinalizadoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class JuegoFinalizadoViewModel
    {
        public string Usuario { get; set; }
        public string Juego { get; set; }
        public IEnumerable<PreguntaEstadisticaViewModel> PreguntaEstadistica { get; set; }
        public int PuntajeTotal { get; set; }
    }
    public class JuegoFinalizadoMobileViewModel
    {
        public Guid IdCategoria { get; set; }
        public string Usuario { get; set; }
        public string Juego { get; set; }
        public IEnumerable<PreguntaEstadisticaViewModel> PreguntaEstadistica { get; set; }
        public int PuntajeTotal { get; set; }
        public string Finalizado { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/PreguntaABMViewModel.cs
using Preguntas.Models.Dominio.ViewModels;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using Preguntas.Models.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.ViewModels.Preguntas
{
    public class PreguntaABMViewModel : EntidadViewModel
    {
        public int Puntaje { get; set; }
        public Guid Juego { get; set; }
        public List<RespuestaABMViewModel> Respuestas { get; set; } //lista de resp
        public List<SelectBoxViewModel> JuegosDisponibles { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/PreguntaEstadisticaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class PreguntaEstadisticaViewModel
    {
        public string PreguntaEstadisticaTexto { get; set; }
        public int PuntajePreguntaEstadistica { get; set; }
        public IEnumerable<RespuestaEstadisticaViewModel> RespuestaEstadistica { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/PreguntaJuegoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class PreguntaJuegoViewModel
    {
        public PreguntaJuegoViewModel() { }
        public Guid JuegoId { get; set; }
        public Guid RespuestaCorrecta { get; set; }
        public PreguntaViewModel PreguntaJuego { get; set; }
        public virtual IEnumerable<RespuestaViewModel> RespuestaJuego { get; set; }
        public Guid RespuestaSeleccionada { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/PreguntaViewModel.cs
using Preguntas.Models.General;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class PreguntaViewModel : EntidadViewModel
    {
        public PreguntaViewModel() { }
        public PreguntaViewModel(ApplicationDbContext db)
        {
            LlenarListas(db);
        }
        public void LlenarListas(ApplicationDbContext db)
        {
            JuegosDisponibles = db.Juegos.Select(j => new SelectBoxViewModel
            {
                Id = j.Id,
                Nombre = j.Nombre
            }).ToList();

            Respuestas = db.Respuestas.Select(r => new RespuestaViewModel
            {
                Id = r.Id,
                Nombre = r.Nombre
            }).ToList();
        }

        public int Puntaje { get; set; }
        public Guid Juego { get; set; }
        public virtual List<SelectBoxViewModel> JuegosDisponibles { get; set; }
        public List<RespuestaViewModel> Respuestas { get; set; }
        public List<Guid> RepuestasDeLaPregunta { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/PreguntasGrillaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class PreguntasGrillaViewModel : EntidadViewModel
    {
        public string Juego { get; set; }
        public int Puntaje { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/RespuestaABMViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class RespuestaABMViewModel : EntidadViewModel
    {
        public bool RespuestaCorrecta { get; set; }
        public Guid PregId { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/RespuestaEstadisticaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class RespuestaEstadisticaViewModel
    {
        public string RespuestaTexto { get; set; }
        public bool EsCorrecta { get; set; }
        public bool RespuestaElegida { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/RespuestaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class RespuestaViewModel : EntidadViewModel
    {
        public bool EsCorrecta { get; set; }
    }
}

Preguntas/Controllers/PreguntaController.cs
using Preguntas.Models;
using Preguntas.Models.Dominio;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using Preguntas.Models.ViewModels.Preguntas;
using System;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web.Mvc;

namespace Preguntas.Controllers
{
    public class PreguntaController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Respuesta
        public ActionResult Index()
        {
            var preguntas = db.Preguntas.Select(Pregunta => new PreguntasGrillaViewModel
            {
                Id = Pregunta.Id,
                Nombre = Pregunta.Nombre,
                Puntaje = Pregunta.Puntaje

            }).ToList();
            return View(preguntas);
        }
        public ActionResult Create()
        {
            return View();
        }

        // Lista de juegos
        public ActionResult ListaJuegos()
        {
            var selectjuegos = db.Juegos.Select(p => new {
                Id = p.Id,
                Nombre = p.Nombre
            }).ToList();
            return Json(new { Result = selectjuegos, Error = "" }, JsonRequestBehavior.AllowGet);
        }

        // Crear Pregunta
        [HttpPost]
        public ActionResult Create(PreguntaABMViewModel preg)
        {
                var pregunta = new Pregunta(preg, db);

                db.Preguntas.Add(pregunta);
                db.SaveChanges();

            return Json(new { Result = "OK", Error = "" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult Delete (Guid Id)
        {
            var preg = db.Preguntas.Find(Id);
            db.Preguntas.Remove(preg);
            db.SaveChanges();

            return Json(new { Result = "OK", Error = "" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(Guid Id)
        {
            var pregunta = db.Preguntas.Find(Id);
            var model = pregunta.CovertirAViewModel();

            return View(model);
        }
    }
}

Preguntas/Views/Pregunta/Create.cshtml
<!-- CREATE Pregunta  -->
<style>
    .modal-backdrop {
        z-index: -1;
    }
</style>
<div class="container">
    <h3>Crear Pregunta</h3>

    <div class="col-md-offset-4 col-md-6">
        <div class="form-group">
            <label for="pregunta">Pregunta </label><input class="form-control" type="text" id="nombre" />
            <br>
            <label for="puntaje">Puntaje</label> <input class="form-control" type="number" id="puntaje" />
            <br />
            <label for="selectjuegos">Juego </label> <div id="ListaJuegos"></div>
            <br />
        </div>

        <!-- MODAL RESPUESTA -->
        <div id="divPrincipal">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Añadir Respuesta</button>
        </div>

        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content animated bounceInRight">
                    <div class="modal-header">
                        <h4 class="modal-title">Crear Respuesta</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group"><label>Respuesta</label> <input style="max-width: 100%; min-width: 100%;" type="text" id="creaResp" class="form-control" /></div>
                        <div class=" checkbox"><label><b>Respuesta correcta</b><input style="max-width: 10%; min-width: 10%;" type="checkbox" id="respBool" /></label></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-white btn-block" data-dismiss="modal">Cancelar</button>
                        <button type="button" class="btn btn-success btn-block" id="btnGuardarresp">Guardar</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- /MODAL RESPUESTAS -->
        <br />
        <h5 class="text-center">Lista de respuestas</h5>

        <table id="tresp" class="table table-striped">
            <tr>
                <th>Respuesta</th>
                <th>Acciones</th>
            </tr>
        </table>
        <!-- ERRORES -->
        <div id="errores" class="alert alert-danger col-md-4" style="display:none">
        </div>
        <br />
        <div class="col-md-6">
            <button class="btn btn-success" id="enviar">Guardar</button>
        </div>

    </div>
</div>

@section Scripts {
    <script src="~/assets/chosen/chosen.jquery.js"></script>
    <link href="~/assets/chosen/chosen.css" rel="stylesheet" />
    <script src="~/assets/sweetalert/sweetalert.min.js"></script>
    <link href="~/assets/sweetalert/sweetalert.css" rel="stylesheet" />

    <script type="text/javascript">

        $(document).ready(function () {

            var pregArr = [];
            var respid = 0;

            function refresh() {
                //borra respuesta

                $('.btnDelete').click(function () {
                    var mID = $(this).attr('id');
                    swal({
                        title: "¿Está seguro de que desea eliminar la preguta?",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Sí",
                        cancelButtonText: "No",
                        closeOnConfirm: true
                    }, function () {
                        for (var i = 0; i < pregArr.length; i++) {
                            if (pregArr[i].ID == mID) {
                                pregArr.splice(i, 1)
                                $('#' + mID).remove();
                                $('.resp' + mID).remove().removeClass(this);
                            }
                        }
                        })
                })
            }
            //Modal de resp Creacion

            $('#btnGuardarresp').click(function () {
                var resp = {
                    Nombre: $('#creaResp').val(),
                    ID: respid,
                    RespuestaCorrecta: $('#respBool').is(":checked")
                }
                respid = respid + 1;
                pregArr.push(resp);
                $('#tresp').off();
                $('#tresp').append('<tr><td class="resp' + resp.ID + '">' + resp.Nombre + '</td>' + '<td><button class="btn btn-primary btnDelete" id="' + resp.ID + '">Borrar</button></td></tr>');
                $('#creaResp').val("");
                $('#respBool').prop('checked', false);
                $('#exampleModal').modal('hide');
                refresh();
            });

             $.ajax({
                type: "GET",
                url: '@Url.Action("ListaJuegos", "Pregunta")',
                success: function (listajuegos) {
                    var juegos = '<select id="selectjuegos"><option value="">-</option>';

                    for (var i = 0; i < listajuegos.Result.length; i++) {
                        juegos += '<option class="juego" value="' + listajuegos.Result[i].Id + '">'
                        juegos += listajuegos.Result[i].Nombre + '</option>'
                    }

                    juegos += '</select>';
                    $("#selectjuegos").off();
                    $("#ListaJuegos").append(juegos);
                    $('#selectjuegos').chosen({ width: '50%' });
                }
            });

            // Almacena los datos de los campos en la variable preg
            $("#enviar").click(function () {
                var preg = {
                    Nombre: $("#nombre").val(),
                    Juego: $('#selectjuegos').val(),
                    Puntaje: $('#puntaje').val(),
                    Respuestas: pregArr
                };
                //POST del metodo Create del cotrolador Restaurante, antes de almacenar ejecuta la funcion validar.
                $.ajax({
                    type: "POST",
                    url: '@(Url.Action("Create", "Pregunta"))',
                    data: { preg: preg },
                    success: function (preg) {
                        preg.Result,
                            location.reload();
                        //validar(resto.Result, resto.Error);
                    }
                })
             });

             // Valida los campos de nombre y direccion
             //function validar(result, error) {
             //    if (result == "OK")
             //        location.reload();
             //    else {
             //        var msg = '<ul>';
             //        for (var i = 0; i < error.length; i++) {
             //            msg += '<li>' + error[i] + '</li >';
             //        }

             //        msg += '</ul>';
             //        $("#errores").html(msg);
             //        $('#errores').css('display', 'block');
             //    }
             //};
        });
    </script>
}

Preguntas/Views/Pregunta/Edit.cshtml
@model Preguntas.Models.Dominio.ViewModels.Preguntas.PreguntaViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @Model.JuegosDisponibles
        @Model.Nombre
        @Model.Puntaje
    </div>
</body>
</html>

Preguntas/Views/Pregunta/Index.cshtml
@model List<Preguntas.Models.Dominio.ViewModels.Preguntas.PreguntasGrillaViewModel>

<div class="container">
    <div class="col-md-12">
        <table class="table" >
            <thead>
                <tr>
                    <th>
                        Pregunta
                    </th>
                    <th>
                        Puntaje
                    </th>
                    <th>
                        Juego
                    </th>
                    <th>
                        Acciones
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pregunta in Model)
                {
                <tr id="@(pregunta.Id)">
                    <td>
                        @(pregunta.Nombre)
                    </td>
                    <td>
                        @(pregunta.Puntaje)
                    </td>
                    @*<td>
                        @foreach(var resp in pregunta.Respuestas){
                            @resp.Nombre
                        }
                    </td>*@
                    <td>
                        <a href="@Url.Action("Edit")/@(pregunta.Id)" class="btn btn-warning">Edit</a><br>
                        <a id="@pregunta.Id" class="btnDelete btn btn-danger">Borrar</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/assets/sweetalert/sweetalert.min.js"></script>
    <link href="~/assets/sweetalert/sweetalert.css" rel="stylesheet" />
    <script type="text/javascript">

        $(document).ready(function () {

            $(".btnDelete").click(function () {
                var idEliminar = $(this).attr('id')
                swal({
                    title: "¿Está seguro de que desea eliminar?",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Sí",
                    cancelButtonText: "No",
                    closeOnConfirm: true
                },function(){

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "Pregunta")',
                    data: { id: idEliminar },
                    success: function (data) {
                        swal("¡Eliminado!", "success"),
                        location.reload()
                    },
                    error: function (error) {
                        sawl("ERROR!", "error")
                    }
                    });
                });
            });
        });
    </script>}