Preguntas/Models/Dominio/Respuesta.cs
using Binit.Infraestructura.Website.Models.Dominio.General;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio
{
    public class Respuesta : Entidad
    {
        public Respuesta() {}
        public Respuesta(RespuestaABMViewModel model)
        {
            Nombre = model.Nombre;
            EsCorrecta = model.RespuestaCorrecta;
        }
        public Respuesta(RespuestaABMViewModel viewmodel, ApplicationDbContext db, Pregunta pregunta)
        {
            Nombre = viewmodel.Nombre;
            if (Preguntas == null)
            {
                Preguntas = new List<Pregunta>();
            }

            Preguntas.Add(pregunta);
        }
        public virtual ICollection<Pregunta> Preguntas { get; set; }
        public bool EsCorrecta { get; set; }
    }
}

Preguntas/Models/Dominio/ViewModels/Preguntas/RespuestaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Preguntas.Models.Dominio.ViewModels.Preguntas
{
    public class RespuestaViewModel : EntidadViewModel
    {
        public bool EsCorrecta { get; set; }
    }
}

Preguntas/Controllers/RespuestaController.cs
using Preguntas.Models;
using Preguntas.Models.Dominio;
using Preguntas.Models.Dominio.ViewModels.Preguntas;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Preguntas.Controllers
{
    public class RespuestaController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Respuesta
        public ActionResult Index()
        {
            var respuestas = db.Respuestas.Select(Respuestas => new RespuestaABMViewModel
            {
                Nombre = Respuestas.Nombre,
            }).ToList();
            return View(respuestas);
        }
        public ActionResult Create()
        {
            var model = new RespuestaABMViewModel();
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(RespuestaABMViewModel model)
        {
            if (ModelState.IsValid)
            {
                var respuestas = new Respuesta(model);
                db.Respuestas.Add(respuestas);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);
        }
        //public ActionResult Edit(Guid id)
        //{
        //    var respuestas = db.Respuestas.Find(id);
        //    var model = respuestas.ConvertirAViewModel();

        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult Edit(RespuestaABMViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var respuestas = db.Respuestas.Find(model.Id);
        //        respuestas.Nombre = model.Respuesta;

        //        db.SaveChanges();

        //        return RedirectToAction("Index");
        //    }

        //    return View(model);
        //}

        //[HttpPost]
        //public ActionResult Delete(Guid id)
        //{
        //    var respuestas = db.Respuestas.Find(id);
        //    db.Respuestas.Remove(respuestas);
        //    db.SaveChanges();

        //    return Json(new { Result = "OK", Error = "" }, JsonRequestBehavior.AllowGet);
        //}
    }
}

Preguntas/Views/Respuesta/Create.cshtml
@model Preguntas.Models.Dominio.ViewModels.Preguntas.RespuestaABMViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Create", "Respuesta", FormMethod.Post, new { @id = "form" }))
            {
            <div class="form-row mt-2">
                <div class="col-md-6 form-group">
                    <label for="Respuesta" class="col-form-label">Respuesta</label>
                    @Html.TextBoxFor(m => m.Respuesta, new { @class = "form-control" })
                    <label for="RespuestaCorrecta">Es una respuesta correcta?</label>
                    @Html.CheckBoxFor(m => m.RespuestaCorrecta)
                </div>
            </div>

                <button class="btn btn-primary">Guardar</button>
        }
    </div>
</body>
</html>